### ISSUE TITLE
network

### ISSUE THREAD

**Issue by ShenZhen0502** [RoboticVisionOrg/unsupervised_depth_estimation#4]
hello,where is the network architecture?

**Comment by btalb** [comment]
Best place to find answers to questions like these will generally be the associated paper.

I believe Figure 3 in the [cited paper](https://arxiv.org/pdf/1603.04992v2.pdf) mentioned [in the README](https://github.com/best-of-acrv/unsupervised-depth-estimation#citing-our-work)  should help you out here.
